#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

# Install useful stuff
sudo apt update
sudo apt install -y build-essential vim terminator git make zsh wget fonts-powerline meld silversearcher-ag
sudo snap install emacs --classic

# Spacemacs config
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d # Spacemacs
cd $HOME/.emacs.d
git remote add fork https://github.com/FilMarini/spacemacs.git
git fetch fork
git checkout vhdl-layer-dev


# Install O-M-Z
export RUNZSH=no
export KEEP_ZSHRC=yes
sh -c "$(wget -qO- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# ZSH config files
ZSH_CUSTOM_TARGET="$HOME/.oh-my-zsh/custom"
ZSH_CUSTOM_ORIGIN="$HOME/.config/omz"

for file in $ZSH_CUSTOM_ORIGIN/*.zsh; do
        fileName=$(basename ${file})
        ln -s $file $ZSH_CUSTOM_TARGET/$fileName
done

# O-M-Z Plugins
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

