#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

# Install useful stuff
sudo apt update
sudo apt install -y build-essential vim terminator git make zsh wget
sudo snap install emacs
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d # Spacemacs

# Install O-M-Z
wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
chmod +x install.sh
./install.sh --unattended
rm install.sh

# ZSH config files
ZSH_CUSTOM_TARGET="$HOME/.oh-my-zsh/custom"
ZSH_CUSTOM_ORIGIN="$HOME/.config/omz"

for file in $ZSH_CUSTOM_ORIGIN/*.zsh; do
        fileName=$(basename ${file})
        ln -s $file $ZSH_CUSTOM_TARGET/$fileName
done

# O-M-Z Plugins
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# Restore user files
yadm reset --hard
